services:
  fuseki:
    build:
      context: .
      dockerfile: Dockerfile
    image: fuseki
    ports:
      - "3030:3030"
    volumes:
      - ./run:/fuseki/run
      - ./tmp:/fuseki/tmp
      - ./shiro.ini:/fuseki/run/shiro.ini
    environment:
      FUSEKI_ADMIN_USER: admin
      FUSEKI_ADMIN_PASSWORD: admin