
services:
  fuseki:
    build:
      context: .
      dockerfile: Dockerfile
    image: fuseki
    ports:
      - "3030:3030"
    volumes:
      # - ./jena-lib:/opt/jena
      - ./run:/fuseki/run
      - ./tmp:/fuseki/tmp

#volumes:
