services:
  fuseki:
    build:
      context: .
      dockerfile: Dockerfile
    image: fuseki
    ports:
      - "3030:3030"
    volumes:
      # - ./config.ttl:/fuseki/run/config.ttl
      - ./shiro.ini:/fuseki/run/shiro.ini
      - ./tmp:/fuseki/tmp
    environment:
      FUSEKI_ADMIN_USER: admin
      FUSEKI_ADMIN_PASSWORD: admin